ruddock/modules/rotation/__init__.py
import flask
blueprint = flask.Blueprint('rotation', __name__,
                template_folder='templates', static_folder='static')

import ruddock.modules.rotation.routes

ruddock/modules/rotation/routes.py
import json
import flask
import io

from ruddock.resources import Permissions
from ruddock.decorators import login_required
from ruddock.modules.rotation import blueprint, helpers

PREFROSH_SUBDIR = "prefrosh_pics"

@blueprint.route('/')
@login_required(Permissions.ROTATION)
def show_portal():
  """The portal for all rotation pages."""
  dinner_list = helpers.DINNERS
  buckets = helpers.BUCKETS
  return flask.render_template('portal.html',
    dinner_list=dinner_list, buckets=buckets)

@blueprint.route('/directory')
@login_required(Permissions.ROTATION)
def show_prefrosh_list():
  """Shows a list of prefrosh, possibly restricted to a particular dinner."""
  dinner_id = flask.request.args.get('dinner_id')
  if dinner_id is None or int(dinner_id) not in helpers.DINNERS:
    prefrosh_list = helpers.get_all_prefrosh()
  else:
    dinner_id = int(dinner_id)
    prefrosh_list = helpers.get_prefrosh_by_dinner(dinner_id)
  return flask.render_template('directory.html',
    prefrosh_list=prefrosh_list, dinner_id=dinner_id)

@blueprint.route('/images/<int:prefrosh_id>')
@login_required(Permissions.ROTATION)
def serve_image(prefrosh_id):
  """Retrieves a prefrosh's picture."""
  img_name = helpers.get_image_name(prefrosh_id)
  dir_name = flask.current_app.config["MEDIA_FOLDER"] + '/' + PREFROSH_SUBDIR
  return flask.send_from_directory(dir_name, img_name);

#TODO(henry) fail gracefully when prefrosh has no dinner
@blueprint.route('/prefrosh/<int:prefrosh_id>')
@login_required(Permissions.ROTATION)
def show_prefrosh(prefrosh_id):
  """Shows a particular prefrosh, their votes, and comments."""
  dinner_prefrosh = helpers.get_dinner_prefrosh_by_prefrosh_id(prefrosh_id)
  prefrosh, prev_id, next_id = helpers.get_prefrosh_and_adjacent(prefrosh_id, dinner_prefrosh)
  full_name = helpers.format_name(
    prefrosh['first_name'], prefrosh['last_name'], prefrosh['preferred_name'])

  return flask.render_template('prefrosh.html', full_name=full_name, prefrosh=prefrosh,
            prev_id=prev_id, next_id=next_id, vote_tuples=helpers.VOTE_TUPLES)

@blueprint.route('/update_info/<int:prefrosh_id>', methods=['POST'])
@login_required(Permissions.ROTATION)
def update_comment(prefrosh_id):
  """Submission endpoint for updating feedback on a prefrosh."""
  helpers.update_comments(prefrosh_id, flask.request.form.get("comments", ""))
  helpers.update_votes(prefrosh_id, flask.request.form)
  return flask.redirect(flask.url_for("rotation.show_prefrosh", prefrosh_id=prefrosh_id))

@blueprint.route('/compute_buckets', methods=['POST'])
@login_required(Permissions.ROTATION)
def compute_buckets():
  helpers.compute_buckets()
  return flask.redirect(flask.url_for("rotation.show_portal"))

@blueprint.route('/move')
@login_required(Permissions.ROTATION)
def move():
  """The move up / move down interface."""
  old_bucket_name = flask.request.args.get("old_bucket_name")
  new_bucket_name = flask.request.args.get("new_bucket_name")
  if old_bucket_name not in helpers.BUCKETS or new_bucket_name not in helpers.BUCKETS:
    flask.flash("Bad value for one of the buckets.")
    return flask.redirect(flask.url_for('rotation.show_portal'))
  elif old_bucket_name == new_bucket_name:
    flask.flash("Buckets must be distinct.")
    return flask.redirect(flask.url_for('rotation.show_portal'))
  else:
    old_bucket_prefrosh = helpers.get_prefrosh_by_bucket(old_bucket_name)
    new_bucket_prefrosh = helpers.get_prefrosh_by_bucket(new_bucket_name)
    return flask.render_template('move.html', old_bucket=old_bucket_prefrosh,
      new_bucket=new_bucket_prefrosh, old_bucket_name=old_bucket_name, new_bucket_name=new_bucket_name,
      vote_tuples=helpers.VOTE_TUPLES)

@blueprint.route('/move/change_bucket/<int:prefrosh_id>', methods=['POST'])
@login_required(Permissions.ROTATION)
def change_bucket(prefrosh_id):
  """Submission endpoint for moving prefrosh between buckets."""
  new_bucket_name = flask.request.form.get("newBucket")
  old_bucket_name = flask.request.form.get("oldBucket")
  if old_bucket_name not in helpers.BUCKETS or new_bucket_name not in helpers.BUCKETS:
    flask.flash("Bad value for one of the buckets.")
  elif old_bucket_name == new_bucket_name:
    flask.flash("Buckets must be distinct.")
  old_bucket_prefrosh = helpers.get_prefrosh_by_bucket(old_bucket_name)
  prefrosh, prev_id, next_id = helpers.get_prefrosh_and_adjacent(prefrosh_id, old_bucket_prefrosh)
  helpers.change_bucket(prefrosh_id, new_bucket_name)
  if prev_id:
    return flask.redirect(flask.url_for("rotation.move",
      _anchor=prev_id, old_bucket_name=old_bucket_name, new_bucket_name=new_bucket_name))
  else:
    return flask.redirect(flask.url_for("rotation.move",
      _anchor=next_id, old_bucket_name=old_bucket_name, new_bucket_name=new_bucket_name))

ruddock/modules/rotation/templates/directory.html
{% extends "layout.html" %}

{% block body %}
<script src="{{ url_for('static', filename='js/tablesort.min.js') }}"></script>
<h2>Prefrosh Directory {{ '(Dinner %d)' % dinner_id if dinner_id is not none else '(All)' }}</h2>
<a href="{{ url_for('rotation.show_portal') }}">Return to Portal</a>
<table class="prefroshlist" id="user-table">
  <thead style="cursor: pointer;">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Bucket</th>
      <th>-2</th>
      <th>-1</th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
  {% for prefrosh in prefrosh_list %}
    <tr class="link" onclick="location.href='{{ url_for('rotation.show_prefrosh',
      prefrosh_id=prefrosh['prefrosh_id']) }}'">
    <td>
      <img src="{{ url_for('rotation.serve_image', prefrosh_id=prefrosh['prefrosh_id']) }}"
      height = "200">
    </td>
    <td>{{ prefrosh['full_name'] }}</td>
    <td>{{ prefrosh['bucket_name'] }}</td>
    <td>{{ prefrosh['votes_neg_two'] }}</td>
    <td>{{ prefrosh['votes_neg_one'] }}</td>
    <td>{{ prefrosh['votes_zero'] }}</td>
    <td>{{ prefrosh['votes_plus_one'] }}</td>
    <td>{{ prefrosh['votes_plus_two'] }}</td>
    <td>{{ prefrosh['votes_plus_three'] }}</td>
  </tr>
  {% endfor %}
</table>

<script>
  new Tablesort(document.getElementById('user-table'));
</script>
{% endblock body %}

ruddock/modules/rotation/templates/move.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('rotation.static', filename='css/move.css') }}" />
{% endblock head %}

{% block body %}
<script>
function updateComment(name, comment) {
  document.getElementById("commentName").innerHTML = name;
  document.getElementById("commentBody").innerHTML = comment;
}
</script>

<div class="container">
  <div>
    <h2>Bucket {{ old_bucket_name }}</h2>
    <div class="bucketContents">
      {% for prefrosh in old_bucket %}
        <div class="prefroshDetails" id="{{ prefrosh['prefrosh_id'] }}">
          <img src="{{ url_for('rotation.serve_image', prefrosh_id=prefrosh['prefrosh_id']) }}"
        height = "300">
          <a class="prefroshName" href="{{ url_for('rotation.show_prefrosh',
        prefrosh_id=prefrosh['prefrosh_id']) }}">{{ prefrosh['full_name'] }}</a>
          <div class="container">
            <table>
              <thead>
                <tr>
                  {% for vote_tuple in vote_tuples %}
                    <th>{{ vote_tuple['vote_value'] }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                <tr>
                  {% for vote_tuple in vote_tuples %}
                    <td>{{ prefrosh[vote_tuple['vote_string']] }}</td>
                  {% endfor %}
                </tr>
              </tbody>
            </table>
            <button onclick="updateComment('{{ prefrosh['first_name'] }}',
                              '{{ prefrosh['escaped_comments'] }}')">Comments</button>
            <form action="{{ url_for('rotation.change_bucket', prefrosh_id=prefrosh['prefrosh_id']) }}"
              method="post" id="change_bucket_form">
              <input type="hidden" name="oldBucket" value="{{ old_bucket_name }}">
              <input type="hidden" name="newBucket" value="{{ new_bucket_name }}">
              <input type="submit" value="Move">
            </form>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div>
    <a href="{{ url_for('rotation.show_portal') }}">Return To Portal</a>
    <h4>Comments For: <span id="commentName"></span></h4>
    <br>
    <div id="commentBody"></div>
  </div>
  <div>
    <h2>Bucket {{ new_bucket_name }}</h2>
    <div class="bucketContents">
      {% for prefrosh in new_bucket %}
        <div class="prefroshDetails" id="{{ prefrosh['prefrosh_id'] }}">
          <img src="{{ url_for('rotation.serve_image', prefrosh_id=prefrosh['prefrosh_id']) }}"
        height = "300">
          <a class="prefroshName" href="{{ url_for('rotation.show_prefrosh',
        prefrosh_id=prefrosh['prefrosh_id']) }}">{{ prefrosh['full_name'] }}</a>
          <div class="container">
            <table>
              <thead>
                <tr>
                  {% for vote_tuple in vote_tuples %}
                    <th>{{ vote_tuple['vote_value'] }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                <tr>
                  {% for vote_tuple in vote_tuples %}
                    <td>{{ prefrosh[vote_tuple['vote_string']] }}</td>
                  {% endfor %}
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock body %}

ruddock/modules/rotation/templates/portal.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('rotation.static', filename='css/portal.css') }}" />
{% endblock head %}

{% block body %}
<div class="container">
  <div class="menuItem">
    <h2>Dinners</h2>
    {% for dinner in dinner_list %}
      <a href="{{ url_for('rotation.show_prefrosh_list', dinner_id=dinner) }}">Dinner {{ dinner }}</a>
      <br>
    {% endfor %}
    <a href="{{ url_for('rotation.show_prefrosh_list') }}">All Prefrosh</a>
  </div>
  <div class="menuItem">
    <h2>Compute Buckets</h2>
    <form action = "{{ url_for('rotation.compute_buckets') }}" method = "post">
        <input type="submit" value="Go!">
    </form>
    <br>
    <h2>Move Prefrosh</h2>
    <form action="{{ url_for('rotation.move') }}" method="get" id="bucket_form">
      <label>Old Bucket:</label>
      <select name="old_bucket_name">
        {% for bucket in buckets %}
          <option value="{{ bucket }}">{{ bucket }}</option>
        {% endfor %}
      </select>
      <br>
      <label>New Bucket:</label>
      <select name="new_bucket_name">
        {% for bucket in buckets %}
          <option value="{{ bucket }}">{{ bucket }}</option>
        {% endfor %}
      </select>
      <br>
      <input type="submit" value="Compare Buckets">
    </form>
  </div>
</div>


{% endblock body %}

ruddock/modules/rotation/templates/prefrosh.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('rotation.static', filename='css/prefrosh.css') }}" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
{% endblock head %}

{% block body %}
<script src="{{ url_for('static', filename='js/tablesort.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.are-you-sure.js') }}"></script>
<script>
  $(function() {
    $('form').areYouSure( {'message': 'You have unsaved votes/comments!'} );
  });
</script>

{% if prefrosh['dinner'] is not none %}
  <a href="{{ url_for('rotation.show_prefrosh_list', dinner_id=prefrosh['dinner']) }}">Return to Dinner</a>
{% endif %}
{% if prev_id is not none %}
  <br>
  <a href ="{{ url_for('rotation.show_prefrosh', prefrosh_id=prev_id) }}">Prev</a>
{% endif %}
{% if next_id is not none %}
  <br>
  <a href ="{{ url_for('rotation.show_prefrosh', prefrosh_id=next_id) }}">Next</a>
{% endif %}

<h1>{{ full_name }}</h1>
<div class="container">
  <div>
    <img src="{{ url_for('rotation.serve_image', prefrosh_id=prefrosh['prefrosh_id']) }}"
      height = "550">
    <table style="font-size: 20px;">
      <thead>
        <tr>
          <th>Bucket</th>
          <th>-2</th>
          <th>-1</th>
          <th>0</th>
          <th>1</th>
          <th>2</th>
          <th>3</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ prefrosh['bucket_name'] }}</td>
          {% for vote_tuple in vote_tuples %}
            <td>{{ prefrosh[vote_tuple['vote_string']] }}</td>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>
  <div>
    <form action="{{ url_for('rotation.update_comment', prefrosh_id=prefrosh['prefrosh_id']) }}"
        method="post"
        id="comment_form">
      <label>
        <textarea name="comments" class="commentInput"
              rows="25">{{ prefrosh['comments'] if prefrosh['comments'] is not none else '' }}</textarea>
      </label>
      <div class="container">
        {% for vote_tuple in vote_tuples %}
          <div class="voteBlock">
            <label class="voteLabel">{{ vote_tuple['vote_value'] }}</label>
            <br>
            <input class="voteStepper" type="number" name="{{ vote_tuple['vote_string'] }}"
                 step="1" value="{{ prefrosh[vote_tuple['vote_string']] }}">
          </div>
        {% endfor %}
        <input type="submit">
      </div>
    </form>
  </div>
</div>
{% endblock body %}