ruddock/modules/budget/__init__.py
import flask
blueprint = flask.Blueprint('budget', __name__,
  template_folder='templates', static_folder='static')

import ruddock.modules.budget.routes

ruddock/modules/budget/routes.py
import flask

from datetime import datetime  # ugh

from ruddock.resources import Permissions
from ruddock.decorators import login_required, get_args_from_form
from ruddock.modules.budget import blueprint, helpers
from .helpers import PaymentType


@blueprint.route('/')
@login_required(Permissions.BUDGET)
def route_portal():
  """Displays the budget portal."""
  return flask.render_template('budget_portal.html')


@blueprint.route('/summary')
@login_required(Permissions.BUDGET)
def route_summary():
  """Displays account and budget summaries."""

  fyear, is_current = helpers.select_fyear_info(
    flask.request.args.get("fyear", None)
  )

  fyear_id = fyear["fyear_id"]
  fyear_num = fyear["fyear_num"]

  fyear_options = [(r["fyear_num"], r["fyear_id"]) for r in helpers.get_fyears()]
  fyear_options.sort(key=lambda x: x[0], reverse=True)

  a_summary = helpers.get_account_summary()
  b_summary = helpers.get_budget_summary(fyear_id)

  return flask.render_template('summary.html',
    a_summary=a_summary,
    b_summary=b_summary,
    fyear_num=fyear_num,
    is_current=is_current,
    fyear_options=fyear_options)


@blueprint.route('/expenses')
@login_required(Permissions.BUDGET)
def route_expenses():
  """Displays list of expenses."""
  return flask.render_template('expenses.html',
    expenses=helpers.get_transactions(),
    ptypes=PaymentType.get_all())


@blueprint.route('/payments')
@login_required(Permissions.BUDGET)
def route_payments():
  """Displays list of payments."""
  return flask.render_template('payments.html',
    payments=helpers.get_payments(),
    ptypes=PaymentType.get_all())


@blueprint.route('/add_expense')
@login_required(Permissions.BUDGET)
def route_add_expense():
  """Provides an interface for submitting an expense."""

  fyear, is_current = helpers.select_fyear_info(
    flask.request.args.get("fyear", None)
  )

  fyear_id = fyear["fyear_id"]
  fyear_num = fyear["fyear_num"]

  fyear_options = [(r["fyear_num"], r["fyear_id"]) for r in helpers.get_fyears()]
  fyear_options.sort(key=lambda x: x[0], reverse=True)

  # Get the lists for the dropdown menus
  budgets_list = helpers.get_budget_list(fyear_id)
  payment_types = PaymentType.get_all()
  accounts = helpers.get_accounts()
  payees = helpers.get_payees()

  return flask.render_template('add_expense.html',
    budgets=budgets_list,
    payment_types=payment_types,
    accounts=accounts,
    payees=payees,
    fyear_options=fyear_options,
    fyear_num=fyear_num,
    is_current=is_current)


@blueprint.route('/add_expense/submit', methods=['POST'])
@login_required(Permissions.BUDGET)
@get_args_from_form()
def route_submit_expense(budget_id, date_incurred, amount, description,
    payee_id, new_payee, payment_type, account_id, check_no, defer_payment):
  """Sends the expense to the database."""

  # Checkboxes aren't sent as bools... :(
  defer_payment = defer_payment is not None

  # Server side validation
  valid_expense = helpers.validate_expense(budget_id, date_incurred, amount,
      description)
  valid_payment = helpers.validate_payment(payment_type,
      account_id, check_no)
  valid_payee = helpers.validate_payee(payee_id, new_payee)

  errs = helpers.test_predicates((
    (valid_expense, True,              "Invalid expense."),
    (valid_payment, not defer_payment, "Invalid payment."),
    (valid_payee,   defer_payment,     "Invalid payee."  )
  ))

  if errs:
    return flask.redirect(flask.url_for("budget.route_add_expense"))


  transaction = flask.g.db.begin()
  try:
    # This next part depends on whether we are deferring payment or not.
    # If so, then we leave the payment ID null, cause it the corresponding
    # payment hasn't been made yet. However, we require the payee. If it's a new
    # payee, we have to insert it into the database first.
    # If not, then we need to make a new payment, and use its ID. Payee ID is
    # not needed.
    if defer_payment:
      payee_id = payee_id or helpers.record_new_payee(new_payee)
      payment_id = None
    else:
      date_written = date_incurred  # non-deferred payments are instant
      date_posted = None if payment_type == PaymentType.CHECK.value else date_written

      payee_id = None
      payment_id = helpers.record_payment(
        account_id, payment_type, amount, date_written, date_posted,
        payee_id, check_no)

    # Either way, record the expense
    helpers.record_expense(
        budget_id, date_incurred, description, amount, payment_id, payee_id)
    transaction.commit()
    flask.flash("Expense recorded successfully!")

  except Exception:
      transaction.rollback()
      flask.flash("An unexpected error occurred. Please find an IMSS rep.")

  return flask.redirect(flask.url_for("budget.route_add_expense"))


@blueprint.route('/unpaid')
@login_required(Permissions.BUDGET)
def route_unpaid():
  """
  Displays unpaid expenses, and allows the user to create payments for them.
  """

  payment_types = PaymentType.get_all()
  accounts = helpers.get_accounts()
  expense_groups=helpers.get_unpaid_expenses()
  today = datetime.now().strftime("%Y-%m-%d")

  return flask.render_template('unpaid.html',
    payment_types=payment_types,
    accounts=accounts,
    expense_groups=expense_groups,
    today=today)


@blueprint.route('/unpaid/submit', methods=['POST'])
@login_required(Permissions.BUDGET)
@get_args_from_form()
def route_submit_unpaid(payee_id, payment_type, account_id, check_no,
    date_written):
  """Sends the payment to the database."""

  # The date posted is the same as the date written unless we're using a check
  date_posted = None if (payment_type != PaymentType.CHECK.value) else date_written

  # Server side validation
  total = helpers.get_unpaid_amount(payee_id)
  valid_payment = helpers.validate_payment(payment_type, account_id, check_no)
  has_expenses = (total is not None)

  errs = helpers.test_predicates((
    (valid_payment, True, "Invalid payment."),
    (has_expenses,  True, "This payee has no expenses to reimburse."),
  ))

  if errs:
    return flask.redirect(flask.url_for("budget.route_unpaid"))


  # We use a transaction to make sure we don't submit halfway.
  transaction = flask.g.db.begin()
  try:
    payment_id = helpers.record_payment(
        account_id, payment_type, total, date_written, date_posted,
        payee_id, check_no)
    helpers.mark_as_paid(payee_id, payment_id)
    transaction.commit()
    flask.flash("Payment recorded successfully!")

  except Exception:
    transaction.rollback()
    flask.flash("An unexpected error occurred. Please find an IMSS rep.")

  return flask.redirect(flask.url_for("budget.route_unpaid"))


@blueprint.route('/checks')
@login_required(Permissions.BUDGET)
def route_checks():
  """Displays all undeposited checks."""
  return flask.render_template('checks.html',
    checks=helpers.get_unposted_payments(),
    ptypes=PaymentType.get_all())


@blueprint.route('/checks/submit', methods=['POST'])
@login_required(Permissions.BUDGET)
@get_args_from_form()
def route_process_check(payment_id, date_posted, action):
  """Records a check as deposited."""

  # Server side validation
  unposted_ids = [str(x["payment_id"]) for x in helpers.get_unposted_payments()]

  errs = helpers.test_predicates((
    (payment_id in unposted_ids, True,             "Not a valid payment ID!"),
    (date_posted != "",          action == "Post", "No date entered!"       )
  ))

  # If any of the validation failed
  if errs:
    return flask.redirect(flask.url_for("budget.route_checks"))


  # Decide what to do
  if action == "Post":
    helpers.post_payment(payment_id, date_posted)
    flask.flash("Payment successfully posted!")
  elif action == "Void":
    helpers.void_payment(payment_id)
    flask.flash("Payment successfully voided!")
  else:
    flask.flash("Not a legitimate action!")

  return flask.redirect(flask.url_for("budget.route_checks"))

ruddock/modules/budget/templates/add_expense.html
{% extends "layout.html" %}

{% import 'forms.html' as forms %}


{% block head %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<link rel="stylesheet" type="text/css"
  href="{{ url_for('budget.static', filename='css/forms.css') }}">

<script>
function toggle_defer() {

  var deferred = $("#defer-payment").is(':checked');

  $("#deferred-payment").toggle(deferred);
  $("#direct-payment").toggle(!deferred);
}

$(document).ready(function() {
  toggle_defer();
});
</script>

{% endblock head %}


{% block body %}
<h2>Fiscal Year: {{ fyear_num }}</h2>

<form method="get">
  <select id="fyear_select" name="fyear">
    <option selected disabled hidden>--</option>
    {% for num, id in fyear_options %}
    <option id=id>{{ num }}</option>
    {% endfor %}
  </select>
  <input type="submit" value="Change Year">
</form>

{% if not is_current %}
<p style="color: red"><b>WARNING: This expense will not be filed in the current fiscal year! Be sure that's what you intend.</b></p>
{% endif %}

<form action="{{ url_for('budget.route_submit_expense') }}" method="POST">

  <h2>Expense Info</h2>

  {{ forms.expense(budgets) }}

  <h2>Payment Info</h2>
    <label for="defer-payment">Defer Payment?</label>
    <input type="checkbox" id="defer-payment" name="defer-payment" onclick="toggle_defer()">
  <div id="direct-payment">
    {{ forms.payment(payment_types, accounts) }}
  </div>
  <div id="deferred-payment">
    {{ forms.payee(payees) }}
  </div>

<input type="submit" value="Record Expense">

</form>

{% endblock body %}

ruddock/modules/budget/templates/budget_portal.html
<!-- TODO this is conflicting with the rotation portal! what gives? -->
{% extends "layout.html" %}

{% block body %}

<h2>Budget Tools</h2>

<h3>Inspect</h3>

<ul>
  <li><a href="{{ url_for('budget.route_summary') }}">Accounts/Budgets</a></li>
  <li><a href="{{ url_for('budget.route_expenses') }}">Expenses</a></li>
  <li><a href="{{ url_for('budget.route_payments') }}">Payments</a></li>
  <!-- TODO year summary? -->
  <!-- TODO term report! -->
</ul>

<h3>Modify</h3>

<ul>
  <li><a href="{{ url_for('budget.route_add_expense') }}">Add Expenses</a></li>
  <li><a href="{{ url_for('budget.route_unpaid') }}">Do Payments</a></li>
  <li><a href="{{ url_for('budget.route_checks') }}">Non-Deposited Checks</a></li>
  <!-- make new fiscal year -->
  <!-- edit budget amounts -->
</ul>

{% endblock body %}

ruddock/modules/budget/templates/checks.html
{% extends "layout.html" %}


{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('budget.static', filename='css/forms.css') }}">
{% endblock head %}


{% block body %}

<h2>Process Check</h2>
<form id="form" action="{{ url_for('budget.route_process_check') }}" method="POST">
  <div class="form-row">
    <label for="payment-id">Payment ID: </label>
    <input id="payment-id" name="payment-id" type="text">
  </div>
  <div class="form-row">
    <label for="date-posted">Date Deposited: </label>
    <input id="date-posted" name="date-posted" type="date">
  </div>
  <div class="form-row">
    <input type="submit" name="action" value="Post">
    <input type="submit" name="action" value="Void">
  </div>
</form>

<h2>Non-Deposited Checks</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Account</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Date Written</th>
      <th>Payee</th>
      <th>Check #</th>
    </tr>
  </thead>
  <tbody>
    {% for r in checks %}
    <tr>
      <td>{{ r["payment_id"] }}</td>
      <td>{{ r["account_name"] }}</td>
      <td>{{ ptypes[r["payment_type"]] }}</td>
      <td>${{ r["amount"] }}</td>
      <td>{{ r["date_written"] }}</td>
      <td>{{ r["payee_name"] }}</td>
      <td>{{ r["check_no"] }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock body %}

ruddock/modules/budget/templates/expenses.html
{% extends "layout.html" %}

<!--TODO alter css so that the page is extra-wide-->

{% block body %}

<h2>Expense List</h2>
<table>

  <thead>
    <tr>
      <th>ID</th>
      <th>Budget</th>
      <th>FY</th>
      <th>Date Incurred</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Payment ID</th>
      <th>Payee</th>
      <th>Type</th>
      <th>Account</th>
      <th>Check #</th>
    </tr>
  </thead>

  <tbody>
    {% for r in expenses %}
    <tr>
      <td>{{ r["expense_id"] }}</td>
      <td>{{ r["budget_name"] }}</td>
      <td>{{ r["fyear_num"] }}</td>
      <td>{{ r["date_incurred"] }}</td>
      <td>{{ r["description"] }}</td>
      <td>${{ r["cost"] }}</td>
      <td>{{ r["payment_id"] or "--" }}</td>
      <td>{{ r["payee_name"] or "--" }}</td>
      <td>{{ ptypes[r["payment_type"]] or "--" }}</td>
      <td>{{ r["account_name"] or "--" }}</td>
      <td>{{ r["check_no"] or "--" }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock body %}

ruddock/modules/budget/templates/forms.html
<!-- Fields for an expense: budget, date incurred, amount, description -->
{% macro expense(budgets) %}

<div class="form-row">
  <label for="budget-id">Budget: </label>
  <select id="budget-id" name="budget-id">
    <option value="" selected="selected">-- Select Budget --</option>
    {% for row in budgets %}
      <option value="{{ row["budget_id"] }}">{{ row["budget_name"] }}</option>
    {% endfor %}}
  </select>
</div>
<div class="form-row">
  <label for="date-incurred">Date Incurred: </label>
  <input type="date" id="date-incurred" name="date-incurred">
</div>
<div class="form-row">
  <label for="amount">Amount: </label>
  <input type="text" id="amount" name="amount">
</div>
<div class="form-row">
  <label for="description">Description: </label>
  <textarea id="description" name="description"></textarea>
</div>

{% endmacro %}


<!-- Fields for a payment: type, account, check # -->
{% macro payment(payment_types, accounts) %}

<div class="form-row">
  <label for="payment-type">Payment Type: </label>
  <select id="payment-type" name="payment-type">
    <option value="" selected="selected">-- Select Type --</option>
    {% for i, t in payment_types.items() %}
      <option value={{i}}>{{t}}</option>
    {% endfor %}
  </select>
</div>
<div class="form-row">
  <label for="account-id">Account: </label>
  <select id="account-id" name="account-id">
    <option value="" selected="selected">-- Select Account --</option>
    {% for row in accounts %}
      <option value="{{ row["account_id"] }}">{{ row["account_name"] }}</option>
    {% endfor %}
  </select>
</div>
<div class="form-row">
  <label for="check-no">Check #: </label>
  <input type="number" id="check-no" name="check-no">
</div>

{% endmacro %}


<!-- Fields for payee input, existing or new -->
{% macro payee(payees) %}

<div class="form-row">
  <label for="payee-id">Existing Payee: </label>
  <select id="payee-id" name="payee-id">
    <option value="" selected="selected">-- Select Payee --</option>
    {% for row in payees %}
      <option value="{{ row["payee_id"] }}">{{ row["payee_name"] }}</option>
    {% endfor %}
  </select>
</div>
<div class="form-row">
  <label for="new-payee">or add a new one: </label>
  <input type="text" id="new-payee" name="new-payee">
</div>

{% endmacro %}

ruddock/modules/budget/templates/payments.html
{% extends "layout.html" %}

{% block body %}

<h2>Payment List</h2>
<table>

  <thead>
    <tr>
      <th>ID</th>
      <th>Account</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Date Written</th>
      <th>Date Posted</th>
      <th>Payee</th>
      <th>Check #</th>
    </tr>
  </thead>

  <tbody>
    {% for r in payments %}
    <tr>
      <td>{{ r["payment_id"] }}</td>
      <td>{{ r["account_name"] }}</td>
      <td>{{ ptypes[r["payment_type"]] }}</td>
      <td>${{ r["amount"] }}</td>
      <td>{{ r["date_written"] }}</td>
      <td>{{ r["date_posted"] }}</td>
      <td>{{ r["payee_name"] }}</td>
      <td>{{ r["check_no"] }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock body %}

ruddock/modules/budget/templates/summary.html
{% extends "layout.html" %}

{% block body %}

<h2>
  Fiscal Year: {{ fyear_num }}
  {% if is_current %}
  (Current)
  {% endif %}
</h2>

<form method="get">
  <select id="fyear_select" name="fyear">
    <option selected disabled hidden>--</option>
    {% for num, id in fyear_options %}
    <option id=id>{{ num }}</option>
    {% endfor %}
  </select>
  <input type="submit" value="Change Year">
</form>

<!-- These might look nice side-by-side! -->
<h2>Account Summary</h2>
<table>

  <thead>
    <tr>
      <th>Account Name</th>
      <th>Current Balance</th>
    </tr>
  </thead>

  <tbody>
    {% for r in a_summary %}
    <tr>
      <td>{{ r["account_name"] }}</td>
      <td>${{ r["bal"] }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>


<h2>Budget Summary</h2>

<table>

  <thead>
    <tr>
      <th>Budget Name</th>
      <th>Starting Amount</th>
      <th>Spent</th>
      <th>Remaining</th>
    </tr>
  </thead>

  <tbody>
    {% for r in b_summary %}
    <tr>
      <td>{{ r["budget_name"] }}</td>
      <td>${{ r["starting_amount"] }}</td>
      <td>${{ r["spent"] }}</td>
      <td>${{ r["remaining"] }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock body %}

ruddock/modules/budget/templates/unpaid.html
{% extends "layout.html" %}

{% import "forms.html" as forms %}


{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('budget.static', filename='css/forms.css') }}">
{% endblock head %}


{% block body %}

<h2>Unpaid Expenses</h2>
<hr>
No client side validation for now. If you submit an invalid request, you'll have to start again.
<hr>
{% if expense_groups %}
  {% for payee_id, payee_name, total, expenses in expense_groups %}
    <h3>{{ payee_name }}: ${{ total }}</h3>
    <form action="{{ url_for('budget.route_submit_unpaid') }}" method="POST">
      <!-- hidden input tags so that POST sends this -->
      <input type="hidden" id="payee-id" name="payee-id" value="{{ payee_id }}">
      <!-- visible stuff -->
      {{ forms.payment(payment_types, accounts) }}
      <div class="form-row">
        <label for="date-written">Date Written:</label>
        <input type="date" id="date-written" name="date-written" value={{ today }}>
      </div>

      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Budget</th>
            <th>FY</th>
            <th>Date Incurred</th>
            <th>Description</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {% for r in expenses %}
            <tr>
              <td>{{ r["expense_id"] }}</td>
              <td>{{ r["budget_name"] }}</td>
              <td>{{ r["fyear_num"] }}</td>
              <td>{{ r["date_incurred"] }}</td>
              <td>{{ r["description"] }}</td>
              <td>${{ r["cost"] }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <input type="submit" value="Record Payment">
    </form>
    <hr>
  {% endfor %}
{% else %}
  <h3>All expenses have been paid!</h3>
{% endif %}

{% endblock body %}