ruddock/modules/admin/__init__.py
import flask
blueprint = flask.Blueprint('admin', __name__, template_folder='templates')

import ruddock.modules.admin.routes

ruddock/modules/admin/routes.py
import tempfile
import http.client
import flask
import json

from ruddock import auth_utils
from ruddock import office_utils
from ruddock import member_utils
from ruddock.resources import Permissions
from ruddock.decorators import login_required
from ruddock.modules.admin import blueprint
from ruddock.modules.admin import member_helpers
from ruddock.modules.admin import position_helpers

@blueprint.route('/')
@login_required()
def admin_home():
  """
  Loads a home page for admins, providing links to various tools.
  """
  links = auth_utils.generate_admin_links()
  # If there are no links, they have no business being here so we return an
  # access denied error.
  if len(links) == 0:
    flask.abort(http.client.FORBIDDEN)
  return flask.render_template('admin.html', links=links)

@blueprint.route('/members/add')
@login_required(Permissions.USERS)
def add_members():
  """Displays a form to add new members."""
  return flask.render_template('add_members.html')

@blueprint.route('/members/add/single/confirm', methods=['POST'])
@login_required(Permissions.USERS)
def add_members_single_confirm():
  """Submission endpoint for adding a single member."""
  fname = flask.request.form.get('fname', '')
  lname = flask.request.form.get('lname', '')
  matriculate_year = flask.request.form.get('matriculate_year', '')
  grad_year = flask.request.form.get('grad_year', '')
  uid = flask.request.form.get('uid', '')
  email = flask.request.form.get('email', '')
  membership_desc = flask.request.form.get('membership_desc', '')

  # Check that data was valid.
  new_member = member_helpers.NewMember(fname, lname, matriculate_year, grad_year,
      uid, email, membership_desc)
  new_member_list = member_helpers.NewMemberList([new_member])
  if new_member_list.validate_data():
    return flask.render_template('add_members_confirm.html',
        new_member_list=new_member_list,
        data_string = str(new_member_list))
  return flask.redirect(flask.url_for('admin.add_members'))

@blueprint.route('/members/add/multi/confirm', methods=['POST'])
@login_required(Permissions.USERS)
def add_members_multi_confirm():
  """Submission endpoint for adding multiple members at a time."""
  new_members_file = flask.request.files.get('new_members_file', None)
  if new_members_file is None:
    flask.flash("You must upload a file!")
    return flask.redirect(flask.url_for('admin.add_members'))
  # Save the file to a tempfile so we can parse it.
  f = tempfile.NamedTemporaryFile()
  f.write(new_members_file.read())
  f.flush()
  # Parse and validate the data.
  new_member_list = member_helpers.NewMemberList()
  if new_member_list.parse_csv_file(f.name):
    if new_member_list.validate_data():
      return flask.render_template('add_members_confirm.html',
          new_member_list=new_member_list,
          data_string = str(new_member_list))
  return flask.redirect(flask.url_for('admin.add_members'))

@blueprint.route('/members/add/confirm/submit', methods=['POST'])
@login_required(Permissions.USERS)
def add_members_confirm_submit():
  """Handles new member creation."""
  # Expects new member data to be passed as a CSV string.
  new_member_data = flask.request.form.get('new_member_data', None)
  # Silently verify data. There shouldn't be any errors if everything is being
  # used as intended.
  new_member_list = member_helpers.NewMemberList()
  if new_member_list.parse_csv_string(new_member_data):
    if new_member_list.validate_data(flash_errors=False):
      new_member_list.add_members()
      return flask.redirect(flask.url_for('admin.add_members'))
  # An error happened somewhere.
  flask.flash("An unexpected error was encountered. Please find an IMSS rep.")
  return flask.redirect(flask.url_for('admin.add_members'))

@blueprint.route('/positions/assignments')
@login_required(Permissions.USERS)
def manage_positions():
  """Provides an interface for managing office assignments."""
  return flask.render_template('positions.html',
      current_assignments = office_utils.get_current_assignments(),
      future_assignments = office_utils.get_future_assignments())

@blueprint.route('/positions/assignments/new')
@login_required(Permissions.USERS)
def new_assignment():
  """Provides an interface for adding new assignments."""
  return flask.render_template('new_assignment.html',
      offices = office_utils.get_all_offices())

@blueprint.route('/positions/assignments/new/submit', methods=['POST'])
@login_required(Permissions.USERS)
def new_assignment_submit():
  """Submission endpoint for new assignment."""
  office_id = flask.request.form.get('office_id', '')
  user_id = flask.request.form.get('user_id', '')
  start_date = flask.request.form.get('start_date', '')
  end_date = flask.request.form.get('end_date', '')

  if position_helpers.handle_new_assignment(office_id, user_id,
      start_date, end_date):
    flask.flash("Success!")
    return flask.redirect(flask.url_for('admin.manage_positions'))
  else:
    return flask.redirect(flask.url_for('admin.new_assignment'))

@blueprint.route('/positions/assignments/edit/<int:assignment_id>')
@login_required(Permissions.USERS)
def edit_assignment(assignment_id):
  """Provides an interface for editing an assignment's start/end dates."""
  # Load current details.
  assignment = office_utils.get_assignment(assignment_id)
  if assignment is None:
    flask.flash("Invalid request.")
    return flask.redirect(flask.url_for('admin.manage_positions'))
  return flask.render_template('edit_assignment.html', assignment=assignment)

@blueprint.route('/positions/assignments/edit/<int:assignment_id>/submit',
    methods=['POST'])
@login_required(Permissions.USERS)
def edit_assignment_submit(assignment_id):
  """Submission endpoint for editing an assignment."""
  start_date = flask.request.form.get('start_date', '')
  end_date = flask.request.form.get('end_date', '')
  if position_helpers.handle_edit_assignment(assignment_id, start_date, end_date):
    flask.flash("Success!")
    return flask.redirect(flask.url_for('admin.manage_positions'))
  else:
    flask.flash("Encountered unexpected error. Try again?")
    return flask.redirect(flask.url_for('admin.edit_assignment',
      assignment_id=assignment_id))

@blueprint.route('/positions/assignments/delete/<int:assignment_id>')
@login_required(Permissions.USERS)
def delete_assignment(assignment_id):
  """Confirms request to delete an assignment."""
  # Load assignment details.
  assignment = office_utils.get_assignment(assignment_id)
  if assignment is None:
    flask.flash("Invalid request.")
    return flask.redirect(flask.url_for('admin.manage_positions'))
  return flask.render_template('delete_assignment.html', assignment=assignment)

@blueprint.route('/positions/assignments/delete/<int:assignment_id>/confirm',
    methods=['POST'])
@login_required(Permissions.USERS)
def delete_assignment_submit(assignment_id):
  """Handles a delete request."""
  if position_helpers.handle_delete_assignment(assignment_id):
    flask.flash("Success!")
    return flask.redirect(flask.url_for('admin.manage_positions'))
  else:
    flask.flash("Encountered unexpected error. Try again?")
    return flask.redirect(flask.url_for('admin.delete_assignment',
      assignment_id=assignment_id))

@blueprint.route('/positions/assignments/past')
@login_required(Permissions.USERS)
def past_assignments():
  """Shows past assignments."""
  return flask.render_template('past_positions.html',
      past_assignments = office_utils.get_past_assignments())

@blueprint.route('/ajax/positions/members/get')
@login_required(Permissions.USERS)
def ajax_get_members():
  """Loads a list of all members for member selection."""
  members = position_helpers.get_members()
  # Need to manually convert into list of dicts so it can be converted to json.
  results = list(dict(member) for member in members)
  return json.dumps(results)

@blueprint.route('/ajax/positions/members/search')
@login_required(Permissions.USERS)
def ajax_search_members():
  """Returns a list of user IDs for members who match the search query."""
  query = flask.request.args.get('query', '')
  results = member_utils.search_members_by_name(query)
  return json.dumps(results)

ruddock/modules/admin/templates/add_members.html
{% extends "layout.html" %}

{% block body %}
<h2>Add new members</h2>
Use this to add a single member to the website. All fields are required.<br><br>
<form action="{{ url_for('admin.add_members_single_confirm') }}" method="post">
  <table class="form">
    <tr>
      <td>First Name</td>
      <td><input type="text" name="fname" autofocus /></td>
      <td>Last Name</td>
      <td><input type="text" name="lname" /></td>
    </tr>
    <tr>
      <td>Matriculation Year</td>
      <td><input type="text" name="matriculate_year" /></td>
      <td>Graduation Year</td>
      <td><input type="text" name="grad_year" /></td>
    </tr>
    <tr>
      <td>UID</td>
      <td><input type="text" name="uid" /></td>
      <td>Email</td>
      <td><input type="text" name="email" /></td>
    </tr>
    <tr>
      <td>Membership Type</td>
      <td><select name="membership_desc">
        <option value="full">Full</option>
        <option value="social">Social</option>
        <option value="associate">Associate</option>
        <option value="ra">RA</option>
      </td>
    </tr>
  </table>
  <button type="submit">Submit</button>
</form>
<br>
<br>
Alternatively, if you need to add many users at once, download and fill out the template provided below.
<br>
<br>
<a href="{{ url_for('static', filename='admin/add_members_template.csv') }}">add_members_template.csv</a>
<br>
<br>
Please upload the completed csv file here.
<form action="{{ url_for('admin.add_members_multi_confirm') }}" method="post" enctype="multipart/form-data">
  <input type="file" name="new_members_file" />
  <br>
  <br>
  <button type="submit">Submit</button>
</form>
{% endblock body %}

ruddock/modules/admin/templates/add_members_confirm.html
{% extends "layout.html" %}

{% block body %}
<h2>Add new members</h2>
Are you sure you want to add the following members?
<form action="{{ url_for('admin.add_members_confirm_submit') }}" method="post">
  <table>
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Matriculation Year</th>
        <th>Graduation Year</th>
        <th>UID</th>
        <th>Email</th>
        <th>Membership Type</th>
      </tr>
    </thead>
    <tbody>
      {% for new_member in new_member_list.new_member_list %}
      <tr>
        <td>{{ new_member.first_name }}</td>
        <td>{{ new_member.last_name }}</td>
        <td>{{ new_member.matriculation_year }}</td>
        <td>{{ new_member.graduation_year }}</td>
        <td>{{ new_member.uid }}</td>
        <td>{{ new_member.email }}</td>
        <td>{{ new_member.membership_desc }}</td>
      {% endfor %}
    </tbody>
  </table>
  <br>
  {# Pass along the actual data as a string. #}
  <input type="hidden" name="new_member_data" value="{{ data_string }}" />
  <button type="button"
    onclick="location.href='{{ url_for('admin.add_members') }}'">No</button>
  <button type="submit">Yes</button>
</form>
{% endblock body %}

ruddock/modules/admin/templates/admin.html
{% extends "layout.html" %}

{% block body %}
<h2>Admin tools</h2>
  {% for link in links %}
  <p><a href="{{ link.link }}">{{ link.name }}</a></p>
  {% endfor %}
{% endblock body %}

ruddock/modules/admin/templates/create_account_reminder.html
{% extends "layout.html" %}

{% block body %}
<h2>Send account creation reminder emails</h2>
Do you want to send a reminder email to these people?<br><br>

<form action="" method="post">
  <table>
    <thead><tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
    </tr></thead>
    {% for member in data %}
    <tr>
      <td>{{ member['fname'] }}</td>
      <td>{{ member['lname'] }}</td>
      <td>{{ member['email'] }}</td>
    </tr>
    {% endfor %}
  </table><br>

  <button type="submit" name="state" value="no">No</button>
  <button type="submit" name="state" value="yes">Yes</button>

</form>
{% endblock body %}

ruddock/modules/admin/templates/delete_assignment.html
{% extends "layout.html" %}

{% block body %}
<h2>Manage Positions</h2>
Confirm deleting this assignment?
<br><br>
<form action="{{ url_for('admin.delete_assignment_submit', assignment_id=assignment['assignment_id']) }}" method="POST">
  <table>
    <tr>
      <td>Office:</td>
      <td>{{ assignment['office_name'] }}</td>
    </tr>
    <tr>
      <td>Name:</td>
      <td>{{ assignment['name'] }}</td>
    </tr>
    <tr>
      <td>Start date:</td>
      <td>{{ assignment['start_date'] }}</td>
    </tr>
    <tr>
      <td>End date:</td>
      <td>{{ assignment['end_date'] }}</td>
    </tr>
  </table>
  <br>
  <button type="button" onclick="location.href='{{ url_for('admin.manage_positions') }}'">
    Back
  </button>
  <button type="submit">Confirm</button>
</form>
{% endblock body %}

ruddock/modules/admin/templates/edit_assignment.html
{% extends "layout.html" %}

{% block head %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
/* Makes the select menu blank initially, without providing a blank option. */
$(document).ready(function() {
    $("#office_select").prop("selectedIndex", -1);
});
</script>
{% endblock head %}

{% block body %}
<h2>Manage Positions</h2>
Edit an existing assignment. Start/end dates should default to Feb 1 for elected positions and July 1 for appointed positions.
<br><br>
<form action="{{ url_for('admin.edit_assignment_submit', assignment_id=assignment['assignment_id']) }}" method="POST">
  <table>
    <tr>
      <td>Office:</td>
      <td>{{ assignment['office_name'] }}</td>
    </tr>
    <tr>
      <td>Name:</td>
      <td>{{ assignment['name'] }}</td>
    </tr>
    <tr>
      <td>Start date:</td>
      <td><input type="text" name="start_date" value="{{ assignment['start_date'] }}"
        placeholder="YYYY-MM-DD" /></td>
    </tr>
    <tr>
      <td>End date:</td>
      <td><input type="text" name="end_date" value="{{ assignment['end_date'] }}"
        placeholder="YYYY-MM-DD" /></td>
    </tr>
  </table>
  <br>
  <button type="button" onclick="location.href='{{ url_for('admin.manage_positions') }}'">
    Back
  </button>
  <button type="submit">Submit</button>
</form>
{% endblock body %}

ruddock/modules/admin/templates/new_assignment.html
{% extends "layout.html" %}

{% block head %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
{# CSS and JS for overlays #}
<script src="{{ url_for('static', filename='js/overlay.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/overlay.css') }}" />

<script>
/* Makes the select menu blank initially, without providing a blank option. */
$(document).ready(function() {
    $("#office_select").prop("selectedIndex", -1);
});

/* Provides an interface for selecting a member. */
function showSelectMemberUI() {
  showOverlay();

  var ui = document.createElement("div");
  $(ui).text("Select someone from the list below.");
  $(ui).append("<br><br>");
  var searchInput = document.createElement("input");
  searchInput.type = "text";
  searchInput.id = "memberSearchInput";
  searchInput.placeholder = "Search for a person...";
  $(searchInput).css({
      "width": "90%",
  });
  $(ui).append(searchInput);
  $(ui).append("<br><br>");

  var results = document.createElement("table");
  results.id = "memberSearchResults";
  $(ui).append(results);

  // Load the initial contents of the table.
  $.ajax({
    url: "{{ url_for('admin.ajax_get_members') }}",
    method: "GET",
    dataType: "json",
    success: function(response) {
      for (var i = 0; i < response.length; i++) {
        var member = response[i];
        var row = document.createElement("tr");
        $(row).prop("data-user-id", member.user_id);
        $(row).prop("data-name", member.name);
        var cell = document.createElement("td");
        $(cell).text(member.name);

        // Handle selecting the user.
        $(row).click(selectMember);

        $(row).append(cell);
        $(results).append(row);
      }
    },
  });

  // Set event handler for search input.
  $(searchInput).on("input", filterMembers);

  $(ui).css({
    "padding": "20px",
  });
  $("#overlayWindow").css({
    "height": "60%",
    "overflow": "auto",
  });
  $("#overlayWindow").append(ui);
  centerOverlay();
}

/* Filters the list of members using the search query. */
function filterMembers() {
  var query = $("#memberSearchInput").val();

  // If the query is cleared, everything should be shown.
  if (query.length === 0) {
    $("#memberSearchResults tr").show();
    return;
  }

  // Perform the search using an AJAX request.
  $.ajax({
    url: "{{ url_for('admin.ajax_search_members') }}",
    method: "GET",
    data: {
      query: query,
    },
    dataType: "json",
    success: function(response) {
      $("#memberSearchResults tr").each(function() {
        var user_id = $(this).prop("data-user-id");
        if ($.inArray(user_id, response) > -1) {
          $(this).show();
        } else {
          $(this).hide();
        }
      });
    },
  });
}

/* Executes the logic when a member is actually selected. */
function selectMember() {
  var user_id = $(this).prop("data-user-id");
  var name = $(this).prop("data-name");
  $("#selectedUser").val(user_id);
  $("#selectedName").text(name);
  closeOverlay();
}
</script>
{% endblock head %}

{% block body %}
<h2>Manage Positions</h2>
Add a new assignment to a position. Start/end dates should default to Feb 1 for elected positions and July 1 for appointed positions.
<br><br>
<form action="{{ url_for('admin.new_assignment_submit') }}" method="POST">
  <table>
    <tr>
      <td>Office:</td>
      <td>
        <select id="office_select" name="office_id">
          {% for office in offices %}
          <option value="{{ office['office_id'] }}">
            {{ office['office_name'] }}
          </option>
          {% endfor %}
        </select>
      </td>
    </tr>
    <tr>
      <td>Name:</td>
      <td>
        <input type="hidden" id="selectedUser" name="user_id" value="-1" />
        <span id="selectedName">(None selected)</span>
      </td>
      <td>
        <button type="button" onclick="showSelectMemberUI()">Choose...</button>
      </td>
    </tr>
    <tr>
      <td>Start date:</td>
      <td><input type="text" name="start_date" placeholder="YYYY-MM-DD" /></td>
    </tr>
    <tr>
      <td>End date:</td>
      <td><input type="text" name="end_date" placeholder="YYYY-MM-DD" /></td>
    </tr>
  </table>
  <br>
  <button type="button" onclick="location.href='{{ url_for('admin.manage_positions') }}'">
    Back
  </button>
  <button type="submit">Submit</button>
</form>
{% endblock body %}

ruddock/modules/admin/templates/past_positions.html
{% extends "layout.html" %}
{% import "positionslib.html" as lib %}

{% block body %}
<h2>Manage Positions</h2>
Modify past position assignments.
<br><br>
<button onclick="location.href='{{ url_for('admin.manage_positions') }}'">
  Back to current/future positions
</button>
<br><br>
{{ lib.show_assignments(past_assignments, 'past') }}
{% endblock body %}

ruddock/modules/admin/templates/positions.html
{% extends "layout.html" %}
{% import "positionslib.html" as lib %}

{% block body %}
<h2>Manage Positions</h2>
Add new assignments (assign someone to a position) or modify existing assignments.
<br><br>
<button onclick="location.href='{{ url_for('admin.new_assignment') }}'">
  Create new assignment
</button>
<button onclick="location.href='{{ url_for('admin.past_assignments') }}'">
  Past assignments
</button>
<br><br>
{{ lib.show_assignments(current_assignments, 'current') }}
<br>
{{ lib.show_assignments(future_assignments, 'future') }}
{% endblock body %}

ruddock/modules/admin/templates/positionslib.html
{# Displays a table with all the assignments provided. #}
{# Provided name is used if there are no assignments. #}
{% macro show_assignments(assignments, name) %}
  <h3>{{ name|title }} Assignments</h3>
  {% if assignments %}
    <table>
      <thead>
        <tr>
          <th>Office</th>
          <th>Name</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for assignment in assignments %}
        <tr>
          <td>{{ assignment['office_name'] }}</td>
          <td>{{ assignment['name'] }}</td>
          <td>{{ assignment['start_date'] }}</td>
          <td>{{ assignment['end_date'] }}</td>
          <td>
            <a href="{{ url_for('admin.edit_assignment',
              assignment_id=assignment['assignment_id']) }}">
              Edit
            </a>
          </td>
          <td>
            <a href="{{ url_for('admin.delete_assignment',
              assignment_id=assignment['assignment_id']) }}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
  <p>No {{ name }} assignments</p>
  {% endif %}
{% endmacro %}