ruddock/modules/hassle/__init__.py
import flask
blueprint = flask.Blueprint('hassle', __name__,
    template_folder='templates', static_folder='static')

import ruddock.modules.hassle.routes

ruddock/modules/hassle/routes.py
import json
import flask

from ruddock.resources import Permissions
from ruddock.decorators import login_required
from ruddock.modules.hassle import blueprint, helpers

@blueprint.route('/')
@login_required(Permissions.HASSLE)
def run_hassle():
  """Logic for room hassles."""
  available_participants = helpers.get_available_participants()
  available_rooms = helpers.get_available_rooms()
  rooms_remaining = helpers.get_rooms_remaining()
  events = helpers.get_events_with_roommates()

  return flask.render_template('hassle.html',
      available_participants=available_participants,
      available_rooms=available_rooms,
      events=events,
      alleys=helpers.alleys,
      rooms_remaining=rooms_remaining)

@blueprint.route('/event', methods=['POST'])
@login_required(Permissions.HASSLE)
def hassle_event():
  """Submission endpoint for a new event (someone picks a room)."""
  user_id = flask.request.form.get('user_id', None)
  room_number = flask.request.form.get('room', None)
  roommates = flask.request.form.getlist('roommate_id')

  if user_id is None or room_number is None:
    flask.flash("Invalid request - try again?")
  else:
    roommates = list(r for r in roommates if r != "none")

    # Check for invalid roommate selection.
    if user_id in roommates or len(roommates) != len(set(roommates)):
      flask.flash("Invalid roommate selection.")
    else:
      helpers.new_event(user_id, room_number, roommates)
  return flask.redirect(flask.url_for('hassle.run_hassle'))

@blueprint.route('/restart', defaults={'event_id': None})
@blueprint.route('/restart/<int:event_id>')
@login_required(Permissions.HASSLE)
def hassle_restart(event_id):
  """Handles a restart."""
  if event_id is None:
    helpers.clear_events()
  else:
    helpers.clear_events(event_id)
  return flask.redirect(flask.url_for('hassle.run_hassle'))

@blueprint.route('/new')
@login_required(Permissions.HASSLE)
def new_hassle():
  """Redirects to the first page to start a new room helpers."""
  # Clear old data.
  helpers.clear_all()
  return flask.redirect(flask.url_for('hassle.new_hassle_participants'))

@blueprint.route('/new/participants')
@login_required(Permissions.HASSLE)
def new_hassle_participants():
  """Select participants for the room helpers."""
  # Get a list of all current members.
  members = helpers.get_all_members()
  return flask.render_template('hassle_new_participants.html', members=members)

@blueprint.route('/new/participants/submit', methods=['POST'])
@login_required(Permissions.HASSLE)
def new_hassle_participants_submit():
  """Submission endpoint for hassle participants. Redirects to next page."""
  # Get a list of all participants' user IDs.
  participants = [int(x) for x in flask.request.form.getlist('participants')]
  # Update database with this hassle's participants.
  helpers.set_participants(participants)
  return flask.redirect(flask.url_for('hassle.new_hassle_rooms'))

@blueprint.route('/new/rooms')
@login_required(Permissions.HASSLE)
def new_hassle_rooms():
  """Select rooms available for the room helpers."""
  # Get a list of all rooms.
  rooms = helpers.get_all_rooms()
  return flask.render_template('hassle_new_rooms.html',
      rooms=rooms, alleys=helpers.alleys)

@blueprint.route('/new/rooms/submit', methods=['POST'])
@login_required(Permissions.HASSLE)
def new_hassle_rooms_submit():
  """Submission endpoint for hassle rooms. Redirects to next page."""
  # Get a list of all room numbers.
  rooms = [int(x) for x in flask.request.form.getlist('rooms')]
  # Update database with participating rooms.
  helpers.set_rooms(rooms)
  return flask.redirect(flask.url_for('hassle.new_hassle_confirm'))

@blueprint.route('/new/confirm')
@login_required(Permissions.HASSLE)
def new_hassle_confirm():
  """Confirmation page for new room helpers."""
  participants = helpers.get_participants()
  rooms = helpers.get_participating_rooms()
  return flask.render_template('hassle_new_confirm.html', rooms=rooms, \
      participants=participants, alleys=helpers.alleys)

@blueprint.route('/new/confirm/submit', methods=['POST'])
@login_required(Permissions.HASSLE)
def new_hassle_confirm_submit():
  """Submission endpoint for confirmation page."""
  # Nothing to do, everything is already in the database.
  return flask.redirect(flask.url_for('hassle.run_hassle'))

@blueprint.route('/ajax/rising')
@login_required(Permissions.HASSLE)
def ajax_get_rising_members():
  """AJAX endpoint that returns the user IDs of rising current members."""
  results = list(x['user_id'] for x in helpers.get_rising_members())
  return json.dumps(results)

@blueprint.route('/ajax/frosh')
@login_required(Permissions.HASSLE)
def ajax_get_frosh():
  """AJAX endpoint that returns the user IDs of current frosh."""
  results = list(x['user_id'] for x in helpers.get_frosh())
  return json.dumps(results)

ruddock/modules/hassle/templates/hassle.html
{% extends "layout.html" %}
{% block head %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
function start_new_hassle() {
  var msg = "Are you sure you want to start a new hassle? This will clear all existing hassle data.";
  if (confirm(msg)) {
    location.href = '{{ url_for('hassle.new_hassle') }}';
  }
}

function panic() {
  var msg = "Panic?";
  if (confirm(msg)) {
    location.href = '{{ url_for('hassle.hassle_restart') }}';
  }
}

function restart(event_id) {
  var msg = "Confirm restart?";
  if (confirm(msg)) {
    location.href = '{{ url_for('hassle.hassle_restart') }}' + '/' + event_id;
  }
}

$(document).ready(function() {
  $("#room_select").prop("selectedIndex", -1);
  $("#name_select").prop("selectedIndex", -1);
});
</script>
{% endblock head %}

{% block body %}
<h2>Room Hassle</h2>
<br>
<div>
  <button type="button" onclick="start_new_hassle()">
    Start new hassle
  </button>
  <button type="button" onclick="panic()">
    PANIC
  </button>
  <br><br>
</div>

<h3>Picked rooms</h3>
<div id="events">
  <table>
    <thead>
      <tr>
        {% for alley in alleys %}
        <th style="width: 16%">Alley {{ alley }}</th>
        {% endfor %}
      </tr>
    </thead>
    {# People picked into each alley #}
    <tr>
      {% for alley in alleys %}
      <td>
        <ul>
          {% for event in events %}
            {% if event['alley'] == alley %}
            <li>{{ event['room_number'] }}: {{ event['occupants'] }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </td>
      {% endfor %}
    </tr>
    {# Rooms remaining in each alley #}
    <tr>
      {% for alley in alleys %}
      <td>Rooms remaining: {{ rooms_remaining[alley] }}</td>
      {% endfor %}
    </tr>
  </table>
  <br>
</div>

<div id="event_form">
  <div style="display: inline-block; padding-right: 20px; vertical-align: top">
    <form action="{{ url_for('hassle.hassle_event') }}" method="POST">
      <table class="form">
        <tr>
          <td>Select a room</td>
          <td>
            <select id="room_select" name="room">
              {% for room in available_rooms %}
              <option value="{{ room['room_number'] }}">
              {{ room['room_number'] }}
              </option>
              {% endfor %}
            </select>
          </td>
        </tr>
        <tr>
          <td>Name</td>
          <td>
            <select id="name_select" name="user_id">
              {% for participant in available_participants %}
              <option value="{{ participant['user_id'] }}">
              {{ participant['name'] }}
              </option>
              {% endfor %}
            </select>
          </td>
        </tr>
        <tr>
          <td>Roommate</td>
          <td>
            <select name="roommate_id">
              <option value="none">-- No roommate --</option>
              {% for participant in available_participants %}
              <option value="{{ participant['user_id'] }}">
              {{ participant['name'] }}
              </option>
              {% endfor %}
            </select>
          </td>
        </tr>
        <tr>
          <td>Triple?</td>
          <td>
              <select name="roommate_id">
              <option value="none">-- Not a triple --</option>
              {% for participant in available_participants %}
              <option value="{{ participant['user_id'] }}">
              {{ participant['name'] }}
              </option>
              {% endfor %}
            </select>
          </td>
        </tr>
      </table>
      <button type="submit">Submit</button>
      <br><br>
    </form>
  </div>
  <div style="display: inline-block; vertical-align: top">
    <img src="{{ url_for('static', filename='images/map_with_beds.png') }}"
      alt="Ruddock House Map">
  </div>
</div>

<h3>All events so far</h3>
<ul>
  {% for event in events %}
  <li>{{ event['occupants'] }} picked room {{ event['room_number'] }}. <button onclick="restart({{ event['hassle_event_id'] }})">Restart</button></li>
  {% endfor %}
</ul>
{% endblock body %}

ruddock/modules/hassle/templates/hassle_new_confirm.html
{% extends "layout.html" %}
{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('hassle.static', filename='css/hassle.css') }}" />
{% endblock head %}

{% block body %}
<h2>Start new hassle</h2>
Please verify that the participating members and rooms is correct.<br><br>

<form action="{{ url_for('hassle.new_hassle_confirm_submit') }}" method="POST">
  <div class="table_container">
    {# Members #}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Graduation Year</th>
          <th>Membership Type</th>
        </tr>
      </thead>
      <tbody>
        {% for member in participants %}
        <tr>
          <td>{{ member['name'] }}</td>
          <td>{{ member['graduation_year'] }}</td>
          <td>{{ member['membership_desc'] }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br>
    {# Rooms #}
    {% for alley in alleys %}
      <table class="rooms_table">
        <thead>
          <tr>
            <th>Room</th>
            <th>Alley</th>
          </tr>
        </thead>
        <tbody>
          {% for room in rooms %}
            {% if room['alley'] == alley %}
            <tr>
              <td>{{ room['room_number'] }}</td>
              <td>{{ room['alley'] }}</td>
            </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
    {% endfor %}
  </div>
  <br>
  <button type="button"
    onclick="location.href='{{ url_for('hassle.new_hassle_participants') }}'">
    Edit participants/rooms
  </button>
  <button type="submit">Confirm</button>
</form>
{% endblock body %}

ruddock/modules/hassle/templates/hassle_new_participants.html
{% extends "layout.html" %}
{% block head %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
function clear_selected() {
  $(".participant_checkbox").each(function() {
      this.checked = false;
  });
}

// Helper that selects rows that have values that appear in the data.
function select_rows(data) {
  $(".participant_checkbox").each(function() {
    if (data.indexOf(parseInt(this.value)) >= 0) {
      this.checked = true;
    }
  });
}

function select_rising() {
  clear_selected();
  $.ajax({
    type: "GET",
    url: "{{ url_for('hassle.ajax_get_rising_members') }}",
    dataType: "json",
    success: select_rows
  });
}

function select_frosh() {
  clear_selected();
  $.ajax({
    type: "GET",
    url: "{{ url_for('hassle.ajax_get_frosh') }}",
    dataType: "json",
    success: select_rows
  });
}
</script>
{% endblock head %}

{% block body %}
<h2>Start new hassle</h2>
Select everyone who will be participating in this room hassle.<br><br>
<div>
  <button type="button" onclick="select_rising()">
    Select all rising members
  </button>
  <button type="button" onclick="select_frosh()">
    Select all frosh
  </button>
  <button type="button" onclick="clear_selected()">
    Clear selection
  </button>
</div>
<br>
<form action="{{ url_for('hassle.new_hassle_participants_submit') }}" method="POST">
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Graduation Year</th>
        <th>Membership Type</th>
      </tr>
    </thead>
    <tbody>
      {% for member in members %}
      <tr>
        <td>
          <input class="participant_checkbox" type="checkbox" name="participants"
            value="{{ member['user_id'] }}"
            {{ 'checked' if member['participating'] }} />
        </td>
        <td>{{ member['name'] }}</td>
        <td>{{ member['graduation_year'] }}</td>
        <td>{{ member['membership_desc'] }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <button type="submit">Next</button>
</form>
{% endblock body %}

ruddock/modules/hassle/templates/hassle_new_rooms.html
{% extends "layout.html" %}
{% block head %}
<link rel="stylesheet" type="text/css"
  href="{{ url_for('hassle.static', filename='css/hassle.css') }}" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
function clear_selected() {
  $(".room_checkbox").each(function() {
      this.checked = false;
  });
}

function select_all() {
  $(".room_checkbox").each(function() {
      this.checked = true;
  });
}
</script>
{% endblock head %}
{% block body %}
<h2>Start new hassle</h2>
Select all rooms that will be used in this hassle.<br><br>
<div>
  <button type="button" onclick="select_all()">
    Select all rooms
  </button>
  <button type="button" onclick="clear_selected()">
    Clear selected rooms
  </button>
</div>
<br>
<form action="{{ url_for('hassle.new_hassle_rooms_submit') }}" method="POST">
<div>
  {# Make a table for each alley. #}
  {% for alley in alleys %}
    <table class="rooms_table">
      <thead>
        <tr>
          <th></th>
          <th>Room</th>
          <th>Alley</th>
        </tr>
      </thead>
      <tbody>
        {% for room in rooms %}
          {% if room['alley'] == alley %}
          <tr>
            <td>
              <input class="room_checkbox" type="checkbox"
                name="rooms" value="{{ room['room_number'] }}"
                {{ 'checked' if room['participating'] }} />
            </td>
            <td>{{ room['room_number'] }}</td>
            <td>{{ room['alley'] }}</td>
          </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  {% endfor %}
</div>
<br>
<button type="button"
  onclick="location.href='{{ url_for('hassle.new_hassle_participants') }}'">
  Previous
</button>
<button type="submit">Next</button>
</form>
{% endblock body %}